# coding: utf-8
"""The Infinite Monkey theorem states that a monkey hitting keys at random on a typewriter keyboard for an infinite amount of time will almost surely type a given text, such as the complete works of William Shakespeare. Well, suppose we replace a monkey with a Python function. How long do you think it would take for a Python function to generate just one sentence of Shakespeare? The sentence we’ll shoot for is: “methinks it is like a weasel”

The way we’ll simulate this is to write a function that generates a string that is 28 characters long by choosing random letters from the 26 letters in the alphabet plus the space. We’ll write another function that will score each generated string by comparing the randomly generated string to the goal.

A third function will repeatedly call generate and score, then if 100% of the letters are correct we are done. If the letters are not correct then we will generate a whole new string.To make it easier to follow your program’s progress this third function should print out the best string generated so far and its score every 1000 tries."""

import random


def generate():
    # Generates a 28 character long phrase from alphabet plus a space character containing list
    chars = list('abcdefghijklmnopqrstuvwxyz ')
    sentence = ''
    for n in range(28):
        rand_char = random.choice(chars)
        sentence += rand_char
    return sentence


def compare(gen):
    # Compares the phrase generated by generate() and the goal phrase character by character and returns the score
    goal = 'methinks it is like a weasel'
    score = 0
    match = [goal[char] for char in range(28) if goal[char] == gen[char]]
    score += len(match)
    return score

# print(compare(generate()))


def evaluate(n):
    # Calls generate() amd compare() multiple times and returns the best phrase generated according to the score returned by compare()
    best_sentence = ''
    scores = []
    for i in range(n):
        sent = generate()
        score = compare(sent)
        best_sentence += sent
        scores.append(score)
        if score == 28:
            print('Done!')
            break
        else:
            if i % 1000 == 0:
                print('The score for {}th trial is {} and the generated string is {}'.format(i, score, sent))
    print('-----------------------------------------------------------------------------------------')
    print('The best sentence generated is {} and its score is {}'.format(sent, max(scores)))


evaluate(55000)

#print('The score for {}th trial is {}'.format(10, compare(generate())))
